project_name: cleared

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: cleared
    main: ./cmd/cleared
    binary: cleared
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/cleared-dev/cleared/internal/buildinfo.Version={{.Version}}
      - -X github.com/cleared-dev/cleared/internal/buildinfo.Commit={{.Commit}}
      - -X github.com/cleared-dev/cleared/internal/buildinfo.Date={{.Date}}

archives:
  - id: cleared
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: cleared-dev
    name: cleared
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
